name: Debug Deployment

on:
  workflow_dispatch:
  push:
    branches: [debug]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Debug environment
        run: |
          echo "=== Environment Info ==="
          node --version
          npm --version
          echo "Working directory: $(pwd)"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"

      - name: List files
        run: |
          echo "=== Repository Files ==="
          ls -la
          echo "=== Package.json content ==="
          cat package.json

      - name: Install dependencies
        run: |
          echo "=== Installing Dependencies ==="
          npm ci
          echo "=== Node modules installed ==="
          ls node_modules | head -10

      - name: Check scripts
        run: |
          echo "=== Available NPM Scripts ==="
          npm run

      - name: Run linting (with details)
        run: |
          echo "=== Running ESLint ==="
          npm run lint || echo "Linting failed, continuing..."

      - name: Build project (with details)
        run: |
          echo "=== Building Project ==="
          npm run build
          echo "=== Build completed ==="
        env:
          NODE_ENV: production

      - name: Examine build output
        run: |
          echo "=== Build Output Analysis ==="
          echo "Dist directory contents:"
          ls -la dist/
          echo ""
          echo "Assets directory:"
          ls -la dist/assets/ || echo "No assets directory"
          echo ""
          echo "Index.html content (first 20 lines):"
          head -20 dist/index.html || echo "No index.html found"
          echo ""
          echo "File sizes:"
          du -h dist/*

      - name: Test static files
        run: |
          echo "=== Static Files Test ==="
          # Check if essential files exist
          [ -f dist/index.html ] && echo "✅ index.html exists" || echo "❌ index.html missing"
          [ -d dist/assets ] && echo "✅ assets directory exists" || echo "❌ assets directory missing"

          # Check for common issues
          if [ -f dist/index.html ]; then
            echo "Checking for base href in index.html:"
            grep -n "base href" dist/index.html || echo "No base href found"
            
            echo "Checking for asset references:"
            grep -n "assets/" dist/index.html || echo "No asset references found"
          fi

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-build-output
          path: |
            dist/
            package.json
            vite.config.js
          retention-days: 7
